### ISSUE TITLE
create a todo-like list that keeps track of the fridge's ingredients (inventory)

### ISSUE THREAD

**Issue by loganpowell** [loganpowell/Refrigerecipe#2]
items for research:
- do we use a search to pull in available ingredients and then select from that?
- do we make a matching algorithm, and if so - is there an off-the-shelf solution?
- MVP: exact match only

**Comment by shawnfielding** [comment]
I have a list of ingredients in a table.  Pulled from https://www.ars.usda.gov/northeast-area/beltsville-md/beltsville-human-nutrition-research-center/nutrient-data-laboratory/docs/sr28-download-files/.  The data could probably programatically be cleaned up a bit.  Think it might work?  It would be nice to have them by grouping, but an alpha search would be a good start.  
[ABBREV.xlsx](https://github.com/loganpowell/Refrigerecipe/files/1009935/ABBREV.xlsx) . I want to just make the database, but I we should sequelize it.

**Comment by loganpowell** [comment]
there's also this: https://market.mashape.com/spoonacular/recipe-food-nutrition#autocomplete-ingredient-search it's only free for 50 calls/day though... cheapskates! :D

**Comment by shawnfielding** [comment]
Yeah, I saw that option.  Asked them if we could get access for a month for a project.

**Comment by shawnfielding** [comment]
Sure.
