### ISSUE TITLE
twillio API

### ISSUE THREAD

**Issue by loganpowell** [loganpowell/Refrigerecipe#4]
SMS reminder to buy groceries with shopping list based on your selection the day before

**Comment by shawnfielding** [comment]
What about just adding a reminder on a google calendar?  https://github.com/google/google-api-nodejs-client

**Comment by loganpowell** [comment]
I like that idea. I'm actually really interested in learning Google calendar API and I would be willing to take this if you're not so interested :)

**Comment by lcheng6** [comment]
done.
