### ISSUE TITLE
back-end: matching algorithm

### ISSUE THREAD

**Issue by loganpowell** [loganpowell/Refrigerecipe#5]
find best match between existing fridge inventory and list of recipes (descending by least difference in ingredients)

**Comment by loganpowell** [comment]
Spoonacular gives us a lot of what we need here. The only things left might be:

- Sort the recipes by the least number of ingredients you have to buy (rather than the default, which is how many of the ingredients match)
- take the input from the refrigerator list and turn it into a string composed of comma separated ingredients without spaces

**Comment by lcheng6** [comment]
don't need backend matching algorithm.
