### ISSUE TITLE
research: find a source for recipes

### ISSUE THREAD

**Issue by loganpowell** [loganpowell/Refrigerecipe#7]

**Comment by loganpowell** [comment]
potentials: 
1. Food2Fork makes it easy to find great recipes. Search by name or ingredients. View Top Socially Ranked Recipes: http://food2fork.com/about/api
2. find recipes based on special diets, nutritional requirements, or favorite ingredients: https://market.mashape.com/spoonacular/recipe-food-nutrition
3. find recipes to use ingredients you already have ("what's in your fridge" search): https://spoonacular.com/food-api

**Comment by lcheng6** [comment]
Assignments: 
Liang will take yummly

**Comment by loganpowell** [comment]
I think Yummly is good enough. Hit me up on slack if you'd like to discuss, but I'm going to try to do some testing over the weekend with Spoonacular.
